db:
  host: localhost
  user: bseguert_bd
  password: 
  name: bseguret
website:
  title: AgendSup
  url: http://localhost/agendsup
  version: 1.0.0
  description: Application de gestion de devoirs pour le BUT Informatique.
  language: fr